#!/bin/bash

source ../bags.bashrc
if [ ! -f around_the_table_tilted.bag ]; then
  wget ${DSLAM_BAG_FILE_REPO}/around_the_table_tilted.bag
fi
if [ ! -h stereo_parameters_front.yaml ]; then
  ln -s ../../parameters/kents_turtle_tilted_front.yaml ./stereo_parameters_front.yaml
fi
if [ ! -h stereo_parameters_back.yaml ]; then
  ln -s ../../parameters/kents_turtle_tilted_back.yaml ./stereo_parameters_back.yaml
fi

