#!/bin/bash

source ../bags.bashrc
if [ ! -f rotate.bag ]; then
  wget ${DSLAM_BAG_FILE_REPO}/rotate.bag
fi
if [ ! -h stereo_parameters_front.yaml ]; then
  ln -s ../../parameters/kents_turtle_front.yaml ./stereo_parameters_front.yaml
fi
if [ ! -h stereo_parameters_back.yaml ]; then
  ln -s ../../parameters/kents_turtle_back.yaml ./stereo_parameters_back.yaml
fi

