#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

stereo_parameters=${DIR}/stereo_parameters_front.yaml
#stereo_parameters=${DIR}/stereo_parameters_back.yaml

rosrun dslam_slam_desktop dslam_viewer ${stereo_parameters} "$@"
